MorphingCircle Outline
AlexRoar/MorphingShapes pull request #1
Opened 2022-10-06 16:52 UTC by mlohr

Added support for optional outline for MorphingCircle

2022-10-13 19:56 UTC, AlexRoar requested changes

2022-10-13 19:56 UTC, AlexRoar commented on README.md
> +Added support for optional outline
- [ ] Don't think that this line needs to be in README

2022-10-13 19:56 UTC, AlexRoar commented on README.md
> +            MorphingCircle(outlineColor: .orange, outlineWidth: 10.0)
- [ ] Same thing. I'd suggest keeping README simple

2022-10-13 19:56 UTC, AlexRoar commented on Sources/MorphingShapes/MorphingBackground.swift
> +@available(macOS 11.0, *)
- [ ] Currently, it's version 10.15 in `Package.swift`. Are you sure you need to set macOS version this high?

2022-10-13 19:56 UTC, AlexRoar commented on Sources/MorphingShapes/MorphingCircle.swift
> +    var outlineColor: Color
- [ ] Outline is never changed, use `let`

2022-10-13 19:56 UTC, AlexRoar commented on Sources/MorphingShapes/MorphingCircle.swift
> +    public init(_ size:CGFloat = 300, morphingRange: CGFloat = 30, color: Color = .red, outlineColor: Color = .clear, outlineWidth: Double = 2, points: Int = 4,  duration: Double = 5.0, secting: Doub
- [ ] For compatibility reasons, parameters should be added at the end

2022-10-14 11:51 UTC, closed without merging

2022-10-14 11:51 UTC, mlohr commented
Will submit new pull request with requested changes

2022-10-14 11:57 UTC, mlohr commented
Thanks I have made updates and put in a new pull request

Op do 13 okt. 2022 om 21:56 schreef Aleksandr Dremov <
***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/AlexRoar/MorphingShapes/pull/1#discussion_r995058879>:
>
> > @@ -2,7 +2,7 @@
>
>  Code for https://alexdremov.me/swiftui-advanced-animation/
>
> -
> +Added support for optional outline
>
>
>    - Don't think that this line needs to be in README
>
> ------------------------------
>
> In README.md
> <https://github.com/AlexRoar/MorphingShapes/pull/1#discussion_r995059410>:
>
> > @@ -14,7 +14,8 @@ import MorphingShapes
>  struct ContentView: View {
>      var body: some View {
>          VStack {
> -            MorphingCircle()
> +            // added support for optional outline:
> +            MorphingCircle(outlineColor: .orange, outlineWidth: 10.0)
>
>
>    - Same thing. I'd suggest keeping README simple
>
> ------------------------------
>
> In Sources/MorphingShapes/MorphingBackground.swift
> <https://github.com/AlexRoar/MorphingShapes/pull/1#discussion_r995060527>:
>
> > @@ -9,6 +9,7 @@ import SwiftUI
>  import Foundation
>  import Combine
>
> ***@***.***(macOS 11.0, *)
>
>
>    - Currently, it's version 10.15 in Package.swift. Are you sure you
>    need to set macOS version this high?
>
> ------------------------------
>
> In Sources/MorphingShapes/MorphingCircle.swift
> <https://github.com/AlexRoar/MorphingShapes/pull/1#discussion_r995062082>:
>
> > @@ -94,14 +95,19 @@ public struct MorphingCircle: View & Identifiable & Hashable {
>      let outerSize: CGFloat
>      var color: Color
>      let morphingRange: CGFloat
> +    ///
> +    var outlineColor: Color
>
>
>    - Outline is never changed, use let
>
> ------------------------------
>
> In Sources/MorphingShapes/MorphingCircle.swift
> <https://github.com/AlexRoar/MorphingShapes/pull/1#discussion_r995063253>:
>
> > @@ -117,9 +123,11 @@ public struct MorphingCircle: View & Identifiable & Hashable {
>
>      }
>
> -    public init(_ size:CGFloat = 300, morphingRange: CGFloat = 30, color: Color = .red, points: Int = 4,  duration: Double = 5.0, secting: Double = 2) {
> +    public init(_ size:CGFloat = 300, morphingRange: CGFloat = 30, color: Color = .red, outlineColor: Color = .clear, outlineWidth: Double = 2, points: Int = 4,  duration: Double = 5.0, secting: Double = 2) {
>
>
>    - For compatibility reasons, parameters should be added at the end
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AlexRoar/MorphingShapes/pull/1#pullrequestreview-1141412455>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMV2PNCDIRUHITJORNNYIDWDBSPHANCNFSM6AAAAAAQ62FSV4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>